#!/bin/bash

cp ~/.vimrc ./.vimrc
cp ~/.vim/UltiSnips/*.snippets .
cp -r /mnt/c/Users/Administrator/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState .
cp ~/.zshrc .
git add -A
echo -n  "please enter a commit ->"
read  commit
git commit -m "$commit"
git push
