#!/bin/bash

#cp ~/.vimrc './.vimrc(WSL)'
cp ~/.vimrc ./.vimrc
cp ~/.cgdb/cgdbrc ./cgdbrc
cp ~/.vim/plugged/YouCompleteMe/third_party/ycmd/.ycm_extra_conf.py .
cp ~/.vim/UltiSnips/*.snippets ./Snippets/
cp ~/.zshrc '.zshrc(ubuntu)'
cp -r ~/.config/terminator .
git add -A
echo -n  "please enter a commit ->"
read  commit
git commit -S -m "$commit"
git push
